
backend:
  name: github
  repo: feiko/feiko.io
  branch: master
  site_domain: feiko.netlify.app

media_folder: "/files/images/"
public_folder: "/images/"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SubTitle", name: "lead", widget: "string"}
      - {label: "Intro", name: "intro", widget: "text", default: "small description for on the homepage"}
      - {label: "Description", name: "description", widget: "text", default: "max length: 155"}
      - {label: "Publish Date", name: Published", widget: "datetime"}
      - {label: "Time Minutes", name: minutes", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "ImageCredit", name: "ImageCredit", widget: "string", required: false}
      - {label: "Thumb Image 1:1", name: "thumbImage", widget: "image"}
      - {label: "Published", name: isPost", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "vlog" # Used in routes, e.g., /admin/collections/blog
    label: "Vlog" # Used in the UI
    folder: "/vlog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SubTitle", name: "lead", widget: "string"}
      - {label: "Intro", name: "intro", widget: "text", default: "small description for on the homepage"}
      - {label: "Description", name: "description", widget: "text", default: "max length: 155"}
      - {label: "Publish Date", name: Published", widget: "datetime"}
      - {label: "Time Minutes", name: minutes", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "YoutubeId", name: "youtubeId", widget: "string"} 
      - {label: "Published", name: isPost", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "/input/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", default: "min length: 155, max length: 155"}
      - {label: "Published", name: "isPost", widget: "boolean", default: true}
      - {label: "Navigation Icon Awesome", name: "navIcon", widget: "string", required: false}
      - {label: "Add to Navigation", name: " showInNavbar", widget: "boolean", default: true}     
      - {label: "Body", name: "body", widget: "markdown", required: false}  
  
  - name: "general"
    label: "General"
    files:
      - file: "/input/settings/header.md"
        label: "Header"
        name: "header"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "About Me", name: "description", widget: "text"}
          - label: "Socials"
            name: "socials"
            widget: "list"
            fields:
              - { label: "Link", name: "link", widget: "string" }
              - { label: "IconName", name: "iconName", widget: "string" }
